source=~/.config/mango/conf/settings/autostart.conf
source=~/.config/mango/conf/settings/general.conf
source=~/.config/mango/conf/settings/rules.conf
source=~/.config/mango/conf/input/input.conf
source=~/.config/mango/conf/appearance/appearance.conf
source=~/.config/mango/conf/appearance/animations.conf
source=~/.config/mango/conf/input/monitors.conf
source=~/.config/mango/conf/layouts/dwindle.conf
source=~/.config/mango/conf/layouts/master.conf
source=~/.config/mango/conf/layouts/scoller.conf
source=~/.config/mango/conf/input/binds.conf
source=~/.config/mango/noctalia.conf
