source=~/.config/mango/conf/autostart.conf
source=~/.config/mango/conf/general.conf
source=~/.config/mango/conf/rules.conf
source=~/.config/mango/conf/input.conf
source=~/.config/mango/conf/binds.conf
source=~/.config/mango/conf/appearance.conf
source=~/.config/mango/conf/animations.conf
source=~/.config/mango/conf/monitors.conf
source=~/.config/mango/conf/layouts/dwindle.conf
source=~/.config/mango/conf/layouts/master.conf
source=~/.config/mango/conf/layouts/scroller.conf
source=~/.config/mango/noctalia.conf
